version: '3.8'
services:
  garden_api:
    build: .
    command: 'dotnet Inplanticular.Garden-Service.WebAPI.dll --urls=http://*:7002 --environment="Development"'
    restart: unless-stopped
    ports:
      - 7002:7002
    networks:
      - inplanticular_net
    depends_on:
      - garden_database

  garden_database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd123
      POSTGRES_DB: postgres
    networks:
      - inplanticular_net

networks:
  inplanticular_net:
    name: inplanticular_net
    external: true